## Numpy array operatoins

In [29]:
import numpy as np

In [30]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing : ",arr[2:7])
print("with step : ",arr[1:8:2])
print("Negative indexing :",arr[-6])

Basic slicing :  [3 4 5 6 7]
with step :  [2 4 6 8]
Negative indexing : 4


In [31]:
arr_2d=np.array([[1,2,3],
                 [4,6,5],
                 [7,8,9]])
print("specific element: ",arr_2d[1,2])
print("specific element: ",arr_2d[0,2])

print("Entire row:",arr_2d[2])

print("Entire column:",arr_2d[:, 0])

specific element:  5
specific element:  3
Entire row: [7 8 9]
Entire column: [1 4 7]


## sorting 

In [32]:
unsorted=np.array([0,7,1,3,4,1,5,2,6,8])
print("sorted Array :",np.sort(unsorted))

arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]]) # written axis=0 mins sorted matrix in top-down approch (column vise)
print("sorted 2D array by column : ", np.sort(arr_2d_unsorted , axis=0))

arr_2d_unsorted=np.array([[2,1],[1,0],[3,2],[6,5]]) # written axis=1 mins sorted matrix in left-right approch (row vise)
print("sorted 2D array by row :",np.sort(arr_2d_unsorted,axis=1))

sorted Array : [0 1 1 2 3 4 5 6 7 8]
sorted 2D array by column :  [[1 1]
 [2 2]
 [3 3]]
sorted 2D array by row : [[1 2]
 [0 1]
 [2 3]
 [5 6]]


## filter

In [33]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers % 2 == 0]
print("even numbers :" , even_numbers)

even numbers : [ 2  4  6  8 10]


## Filter with mask

In [34]:
mask=numbers > 5
print("numbers grater than 5 : ",numbers[mask])

numbers grater than 5 :  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [35]:
indices=[0,2,6] #in this check index position and return value 
print(numbers[indices])

where_result=np.where(numbers > 5)#check only condition and return value
print(where_result)
print("NP where",  numbers[where_result])



[1 3 7]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [36]:
condition__array=np.where(numbers>5 , numbers*4 , numbers)#but in this check condition if true then execute true part/true/if part otherwise false
print(condition__array)

condition__array=np.where(numbers>5,True,False)
print(condition__array)

[ 1  2  3  4  5 24 28 32 36 40]
[False False False False False  True  True  True  True  True]


In [40]:

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


## Array compatibility

In [43]:
a=np.array([1,2,3])
b=np.array([4,5,6,5])
c=np.array([7,8,9])
print("compatibility shape ",a.shape == b.shape)
print("compatibility shape ",a.shape == c.shape)

compatibility shape  False
compatibility shape  True


## Adding ROW & COLUMN

In [49]:
original=np.array([[1,2],[3,4]])
new_row=np.array([5,6])
with_new_row=np.vstack((original,new_row)) # .vstack--> add row in original matrix
print("Adding new row in matrix : ",with_new_row)

new_column=np.array([[8],[7]])
with_new_col=np.hstack((original,new_column))# .hstack--> add column in original matrix
print("Adding new column in matrix : ",with_new_col)

Adding new row in matrix :  [[1 2]
 [3 4]
 [5 6]]
Adding new column in matrix :  [[1 2 8]
 [3 4 7]]


## Delete row & column

In [51]:
arr=np.array([1,3,4,5,6,3])
deleted=np.delete(arr,4) # in numpy this func. not given deleted value but deleted value remove and given new array 
print("Array after deletion: ",deleted)

Array after deletion:  [1 3 4 5 3]
