## Numpy array and basics
learn about numpy with chai or code

In [2]:
import numpy as np

### creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ",arr_2d)


1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [4]:
py_list=[1,2,3]
print("python list multiplication",py_list * 2)

np_array=np.array([1,2,3]) #elemrnt wise multiplication
print("python array multiplication",np_array * 2)


import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time: ",time.time() - start)

start=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy operation time: ",time.time() - start)

python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]

 List operation time:  0.04335331916809082

 Numpy operation time:  0.003926277160644531


### creating array from scratch

In [5]:
zeros=np.zeros((3,4)) #zeros and ones it's function include in libary directly use it.
print("zeros opration: \n",zeros)

ones=np.ones((4,3))
print("onces operation: \n",ones)

full=np.full((2,2),5) #this function use create array for particular value
print("full operation \n",full)

random=np.random.random((2,3))
print("random operation \n",random)

sequnce=np.arange(0,16,3) #it's same as loop in python(start,end,step)--> for i in range(1,10)
print("sequnce operation \n",sequnce)

zeros opration: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
onces operation: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full operation 
 [[5 5]
 [5 5]]
random operation 
 [[0.77567283 0.22827022 0.2349184 ]
 [0.23405905 0.72524108 0.76838906]]
sequnce operation 
 [ 0  3  6  9 12 15]


### vector,matrix and tensor

In [12]:
vector=np.array([1,2,3])
print("vector: ",vector)

matrix=np.array([[1,2,3],[5,6,7]])
print("\n matrix: \n",matrix)

tensor=np.array([[[1,2],[3,4]], #syntax in numpy array from list -->([[value],[value]])
                        [[5,6],[7,8]]])
print("\n tensor: \n",tensor)

vector:  [1 2 3]

 matrix: 
 [[1 2 3]
 [5 6 7]]

 tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [7]:
arr=np.array([[1,2,3,4],
              [3,5,6,7],
              [4,5,6,5]])
print("shape ",arr.shape)#.shapr , .ndim , .size , .dtype all are properties in numpy
print("Dimension ",arr.ndim)
print("size ",arr.size)#count element in the matrix
print("Dtype ",arr.dtype)


shape  (3, 4)
Dimension  2
size  12
Dtype  int64


### Array reshaping

In [13]:
arr=np.arange(12)
print("original array : \n ",arr)

reshaped=arr.reshape((3,4))
print("reshaped array : \n ",reshaped)

flatted=reshaped.flatten()#return copy of array
print("flatted array : \n ",flatted)

#ravel (returns view, instead of copy)--> return original array
reveled=reshaped.ravel()
print("reveled array : \n ",reveled)

transpose=reshaped.T
print("transpose array :",transpose)


original array : 
  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array : 
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatted array : 
  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reveled array : 
  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
